In [4]:
import pandas as pd

In [9]:
path = "../files/tests/out/csv_concat_test.csv"
df = pd.read_csv(path)

In [11]:
df[df['mix'] == True]

,Unnamed: 0,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,...,video_id,file,version,situation,mix,emotion_1,vocalization,intensity_level,emotion_2,proportions
706,0,1,0,0.00,0.98,1,0.037525,0.341781,-0.939030,-0.142143,...,A220,A220_mix_ang_disg_5050.csv,1,1,True,ang,NaN,0,disg,5050.0
707,1,2,0,0.02,0.98,1,0.035051,0.340429,-0.939617,-0.155807,...,A220,A220_mix_ang_disg_5050.csv,1,1,True,ang,NaN,0,disg,5050.0
708,2,3,0,0.04,0.98,1,0.040302,0.345851,-0.937424,-0.147855,...,A220,A220_mix_ang_disg_5050.csv,1,1,True,ang,NaN,0,disg,5050.0
709,3,4,0,0.06,0.98,1,0.040535,0.344946,-0.937747,-0.151583,...,A220,A220_mix_ang_disg_5050.csv,1,1,True,ang,NaN,0,disg,5050.0
710,4,5,0,0.08,0.98,1,0.041836,0.344222,-0.937956,-0.138173,...,A220,A220_mix_ang_disg_5050.csv,1,1,True,ang,NaN,0,disg,5050.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2600,540,541,0,10.80,0.98,1,0.092694,0.448777,-0.888823,0.021968,...,A220,A220_mix_ang_disg_3070.csv,1,1,True,ang,NaN,0,disg,3070.0
2601,541,542,0,10.82,0.98,1,0.098033,0.455281,-0.884934,0.028268,...,A220,A220_mix_ang_disg_3070.csv,1,1,True,ang,NaN,0,disg,3070.0
2602,542,543,0,10.84,0.98,1,0.099049,0.460804,-0.881957,0.020392,...,A220,A220_mix_ang_disg_3070.csv,1,1,True,ang,NaN,0,disg,3070.0
2603,543,544,0,10.86,0.98,1,0.095215,0.460916,-0.882321,0.012465,...,A220,A220_mix_ang_disg_3070.csv,1,1,True,ang,NaN,0,disg,3070.0
2604,544,545,0,10.88,0.98,1,0.091627,0.460232,-0.883058,0.003260,...,A220,A220_mix_ang_disg_3070.csv,1,1,True,ang,NaN,0,disg,3070.0

In [8]:
df

,Unnamed: 0,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,...,video_id,file,version,mix,emotion_1,vocalization,intensity_level,emotion_2,proportions,situation
0,0,1,0,0.00,0.98,1,0.041166,0.301247,-0.952657,-0.181602,...,A220,A220_adm_p_1.csv,1,False,adm,p,1,NaN,NaN,NaN
1,1,2,0,0.02,0.98,1,0.051925,0.281373,-0.958192,-0.188290,...,A220,A220_adm_p_1.csv,1,False,adm,p,1,NaN,NaN,NaN
2,2,3,0,0.04,0.98,1,0.050509,0.278517,-0.959102,-0.185971,...,A220,A220_adm_p_1.csv,1,False,adm,p,1,NaN,NaN,NaN
3,3,4,0,0.06,0.98,1,0.051062,0.270301,-0.961421,-0.182059,...,A220,A220_adm_p_1.csv,1,False,adm,p,1,NaN,NaN,NaN
4,4,5,0,0.08,0.98,1,0.048621,0.270665,-0.961445,-0.181447,...,A220,A220_adm_p_1.csv,1,False,adm,p,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2787,182,183,0,3.64,0.98,1,0.013828,0.276050,-0.961044,-0.152353,...,A327,A327_ang_v_1_ver1.csv,1,False,ang,v,1,NaN,NaN,NaN
2788,183,184,0,3.66,0.98,1,0.000961,0.253841,-0.967245,-0.098668,...,A327,A327_ang_v_1_ver1.csv,1,False,ang,v,1,NaN,NaN,NaN
2789,184,185,0,3.68,0.98,1,-0.021014,0.238563,-0.970900,-0.118966,...,A327,A327_ang_v_1_ver1.csv,1,False,ang,v,1,NaN,NaN,NaN
2790,185,186,0,3.70,0.98,1,-0.049001,0.227696,-0.972499,-0.139232,...,A327,A327_ang_v_1_ver1.csv,1,False,ang,v,1,NaN,NaN,NaN
2791,186,187,0,3.72,0.98,1,-0.061786,0.205454,-0.976714,-0.155820,...,A327,A327_ang_v_1_ver1.csv,1,False,ang,v,1,NaN,NaN,NaN

In [13]:
df

Empty DataFrame
Columns: []
Index: []

In [2]:
"Filename {} contains error marker, skipping file".format("filename")

'Filename filename contains error marker, skipping file'